name: CI-strapi

on:
  push:
    branches: [main]

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    defaults:
      run:
        working-directory: apps/strapi

    steps:
      - uses: actions/checkout@v5

      - name: ⚙️ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: ⚙️ Enable Corepack
        run: corepack enable

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          cwd: ${{ github.workspace }}/apps/strapi

      - name: 🏗 Build strapi
        run: yarn build
        env:
          DATABASE_FILENAME: data/artist.ci.sqlite.db
